apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80  # Exposed to the outside world
      targetPort: 5000  # Inside container port
  type: LoadBalancer
