name: CD Pipeline for Flask Project

on:
  push:
    branches:
      - prod  # Trigger on merge to the prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes (Minikube)
      run: |
        # Install Minikube and kubectl
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        sudo chmod +x /usr/local/bin/minikube
        sudo apt-get install -y kubectl
        # Start Minikube
        minikube start

    - name: Docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull Docker image from DockerHub
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

    - name: Load Docker image into Minikube
      run: |
        # Load the Docker image into Minikube's Docker daemon
        minikube image load ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

    - name: Deploy to Kubernetes (Minikube)
      run: |
        # Set up kubectl to point to Minikube
        kubectl config use-context minikube
        # Apply Kubernetes deployment and service files
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Expose application (Optional)
      run: |
        kubectl expose deployment my-flask-app --type=LoadBalancer --name=my-flask-app-service
        kubectl get services my-flask-app-service
