name: CI Pipeline for Flask Project

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # You can change the version depending on your project needs

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest  # or any other testing framework you are using

    - name: Build Docker image
      run: |
        cd MLOPS_Project  # Make sure we are in the right directory
        docker build -t my-flask-app .  # Build Docker image from Dockerfile

    - name: Push Docker image to DockerHub
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push my-flask-app
